:uri-github-issues: https://github.com/apple/pkl-intellij/issues/new/choose
:uri-seven-rules: https://cbea.ms/git-commit/#seven-rules
:uri-intellij: https://www.jetbrains.com/idea/download/
:uri-jdk: https://adoptopenjdk.net/releases.html

= Pkl IntelliJ Plugin Contributor's Guide

Welcome to the Pkl community, and thank you for contributing!
This guide explains how to get involved.

* <<Licensing>>
* <<Issue Tracking>>
* <<Pull Requests>>
* <<Maintainers>>

== Licensing

Pkl IntelliJ is released under the Apache 2.0 license.
This is why we require that, by submitting a pull request, you acknowledge that you have the right to license your contribution to Apple and the community, and agree that your contribution is licensed under the Apache 2.0 license.

== Issue Tracking

To file a bug or feature request,
use {uri-github-issues}[GitHub issues].
Be sure to include the following information:

* Context
** What are/were you trying to achieve?
** What's the impact of this bug/feature?

For bug reports, additionally include the following information:

* The plugin version (under Preferences > Plugins > Pkl).
* The JetBrains IDE version information (use the "Copy" button of the "About" dialog).
* The complete error message, including stack trace (if available).
* The simplest possible steps to reproduce.

== Pull Requests

When preparing a pull request, follow this checklist:

 * Imitate the conventions of surrounding code.
 * Verify that the build (`./gradlew build`) succeeds.
 * Follow the {uri-seven-rules}[seven rules] of great Git commit messages:
 ** Separate subject from body with a blank line.
 ** Limit the subject line to 50 characters.footnote:not-enforced[This rule is not enforced in the Pkl IntelliJ project.]
 ** Capitalize the subject line.
 ** Do not end the subject line with a period.
 ** Use the imperative mood in the subject line.
 ** Wrap the body at 72 characters.footnote:not-enforced[]
 ** Use the body to explain what and why vs. how.

IMPORTANT: If you plan to make substantial changes or add new features,
we encourage you to first discuss them with the Pkl team.
This will save time and increases the chance of your pull request being accepted.

== Maintainers

The project’s maintainers (those with write access to the upstream repository) are listed in link:MAINTAINERS.adoc[].
