# TODO remove me after trigger stuff is verified
name: Trigger docsite build
'on':
  push: {}
jobs:
  trigger-downstream-builds:
    if: github.repository_owner == 'apple'
    runs-on: ubuntu-latest
    steps:
      - name: Create app token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: '2078927'
          private-key: ${{ secrets.PKL_CI }}
      - name: Trigger pkl-lang.org build
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |-
          gh workflow run \
            --repo apple/pkl-lang.org \
            --ref main \
            --field source_run="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            main.yml
